#!/bin/bash
# Script to convert .epub to .mobi files with calibre and email to kindle
# .mobi files sent straight to kindle
# requires ssmtp, mpack, calibre
######################################################################################
# Config #######################################################################
######################################################################################

# Email address for kindle
KINDLEEMAIL="andy.nmc@gmail.com"

# Directory to process from
LOC_IN="/home/pi/nfs/volume1/downloads/ebooks/_togo"

# Remove converted/sent files after dealing with them? This will leave no files remaining
# which is fine if you keep a safe copy elsewhere
KEEP_ORIGINAL=No     # Original files will end up in the 'sent' subdir
KEEP_CONVERTED=No    # ... and converted files in the 'converted' subdir


######################################################################################

# Create directories if they don't exist
mkdir "$LOC_IN/processing" -p
PROCESSING="$LOC_IN/processing"

mkdir "$LOC_IN/sent" -p
SENT="$LOC_IN/sent"

mkdir  "$LOC_IN/converted" -p
CONVERTED="$LOC_IN/converted"



# for each file passed, do the thing
for file in "$@"
do
  if [[ -f $file ]]
  then
    if [[ $file == *.mobi ]]
    then
      MOBI=$file
      TITLE=${file%.mobi}
      # send to kindle
      echo "No need to convert $MOBI"
      mv "$MOBI" "$PROCESSING/$MOBI"
      mpack -s "$TITLE" "$PROCESSING/$MOBI" $KINDLEEMAIL
      echo "Email sent to $KINDLEEMAIL"
      if [ $KEEP_ORIGINAL == Yes ]
      then
        echo "Storing sent file: $SENT/$MOBI"
        mv "$PROCESSING/$MOBI" "$SENT/$MOBI"
      else
        echo "Deleting $MOBI"
        rm "$PROCESSING/$MOBI"
      fi
    fi
    if [[ $file == *.epub ]]
    then
      EPUB=$file
      MOBI=${file%.epub}.mobi
      TITLE=${file%.mobi}
      # convert then send to kindle
      echo "Converting .epub to .mobi"
      mv "$EPUB" "$PROCESSING/$EPUB"
      ebook-convert "$PROCESSING/$EPUB" "$PROCESSING/$MOBI"
      mpack -s "$TITLE" "$PROCESSING/$MOBI" $KINDLEEMAIL
      echo "Email sent to $KINDLEEMAIL"
      if [ $KEEP_ORIGINAL == No ]
      then
        echo "Deleting $EPUB"
        rm "$PROCESSING/$EPUB"
      else
        echo "Storing sent file: $SENT/$EPUB"
        mv "$PROCESSING/$EPUB" "$SENT/$EPUB"
      fi
      if [ $KEEP_CONVERTED == No ]
      then
        echo "Deleting $MOBI"
        rm "$PROCESSING/$MOBI"
      else
        echo "Storing $MOBI in $SENT"
        mv "$PROCESSING/$MOBI" "$SENT/$MOBI"
      fi
    fi
  fi
done
